### ISSUE TITLE
pfs8 run-5045 failed (webrtc)

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/scenario-player#692] opened 2021-08-19 07:39 UTC
```
{
  "task": "<TransferTask: {'from': 0, 'to': 3, 'amount': 1000000000000000, 'expected_http_status': 200, 'identifier': 154894150451000002}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "greenlet_name": "orchestration",
  "timestamp": "2021-08-18 19:31:29.812919",
  "exception": "Traceback (most recent call last):\n  File \"/scenario-player/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/scenario-player/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:42039/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0xd87d36705F7278240CA2e9EA14cE6f5f4F051024. Expected 200: {\"errors\": \"Payment couldn't be completed because: PFS: Could not connect to Pathfinding Service (HTTPSConnectionPool(host='pfs.transport01.raiden.network', port=443): Read timed out. (read timeout=10.0))\"}"
}
{
  "task": "<SerialTask: {'name': 'Make payment from 0 to 3 after node4 is stopped', 'tasks': [{'wait_blocks': 1}, {'transfer': {'from': 0, 'to': 3, 'amount': 1000000000000000, 'expected_http_status': 200}}, {'wait_blocks': 1}, {'assert': {'from': 0, 'to': 1, 'total_deposit': 1000000000000000000, 'balance': 999000000000000000}}, {'assert': {'from': 1, 'to': 2, 'total_deposit': 1000000000000000000, 'balance': 999000000000000000}}, {'assert': {'from': 2, 'to': 3, 'total_deposit': 1000000000000000000, 'balance': 999000000000000000}}, {'assert_pfs_iou': {'source': 0, 'amount': 100000000000000000}}]}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "greenlet_name": "orchestration",
  "timestamp": "2021-08-18 19:31:29.814626",
  "exception": "Traceback (most recent call last):\n  File \"/scenario-player/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/scenario-player/scenario_player/tasks/execution.py\", line 36, in _run\n    task()\n  File \"/scenario-player/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/scenario-player/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:42039/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0xd87d36705F7278240CA2e9EA14cE6f5f4F051024. Expected 200: {\"errors\": \"Payment couldn't be completed because: PFS: Could not connect to Pathfinding Service (HTTPSConnectionPool(host='pfs.transport01.raiden.network', port=443): Read timed out. (read timeout=10.0))\"}"
}
{
  "task": "<SerialTask: {'tasks': [{'parallel': {'name': 'Open channels', 'tasks': [{'open_channel': {'from': 0, 'to': 1, 'total_deposit': 1000000000000000000, 'expected_http_status': 201}}, {'open_channel': {'from': 1, 'to': 2, 'total_deposit': 1000000000000000000, 'expected_http_status': 201}}, {'open_channel': {'from': 2, 'to': 3, 'total_deposit': 1000000000000000000, 'expected_http_status': 201}}, {'open_channel': {'from': 4, 'to': 3, 'total_deposit': 1000000000000000000, 'expected_http_status': 201}}, {'open_channel': {'from': 0, 'to': 4, 'total_deposit': 1000000000000000000, 'expected_http_status': 201}}]}}, {'parallel': {'name': 'Deposit in the other directions', 'tasks': [{'deposit': {'from': 1, 'to': 0, 'total_deposit': 1000000000000000000, 'expected_http_status': 200}}, {'deposit': {'from': 2, 'to': 1, 'total_deposit': 1000000000000000000, 'expected_http_status': 200}}, {'deposit': {'from': 3, 'to': 2, 'total_deposit': 1000000000000000000, 'expected_http_status': 200}}, {'deposit': {'from': 3, 'to': 4, 'total_deposit': 1000000000000000000, 'expected_http_status': 200}}, {'deposit': {'from': 4, 'to': 0, 'total_deposit': 1000000000000000000, 'expected_http_status': 200}}]}}, {'parallel': {'name': 'Assert after deposits', 'tasks': [{'assert': {'from': 0, 'to': 1, 'total_deposit': 1000000000000000000, 'balance': 1000000000000000000, 'state': 'opened'}}, {'assert': {'from': 1, 'to': 2, 'total_deposit': 1000000000000000000, 'balance': 1000000000000000000, 'state': 'opened'}}, {'assert': {'from': 2, 'to': 3, 'total_deposit': 1000000000000000000, 'balance': 1000000000000000000, 'state': 'opened'}}, {'assert': {'from': 0, 'to': 4, 'total_deposit': 1000000000000000000, 'balance': 1000000000000000000, 'state': 'opened'}}, {'assert': {'from': 4, 'to': 3, 'total_deposit': 1000000000000000000, 'balance': 1000000000000000000, 'state': 'opened'}}, {'assert': {'from': 1, 'to': 0, 'total_deposit': 1000000000000000000, 'balance': 1000000000000000000, 'state': 'opened'}}, {'assert': {'from': 2, 'to': 1, 'total_deposit': 1000000000000000000, 'balance': 1000000000000000000, 'state': 'opened'}}, {'assert': {'from': 3, 'to': 2, 'total_deposit': 1000000000000000000, 'balance': 1000000000000000000, 'state': 'opened'}}, {'assert': {'from': 4, 'to': 0, 'total_deposit': 1000000000000000000, 'balance': 1000000000000000000, 'state': 'opened'}}, {'assert': {'from': 3, 'to': 4, 'total_deposit': 1000000000000000000, 'balance': 1000000000000000000, 'state': 'opened'}}]}}, {'serial': {'name': 'Make payment from 0 to 3', 'tasks': [{'wait_blocks': 1}, {'transfer': {'from': 0, 'to': 3, 'amount': 1000000000000000, 'expected_http_status': 200}}, {'wait_blocks': 1}, {'assert': {'from': 0, 'to': 4, 'total_deposit': 1000000000000000000, 'balance': 999000000000000000}}, {'assert': {'from': 4, 'to': 3, 'total_deposit': 1000000000000000000, 'balance': 999000000000000000}}, {'assert': {'from': 0, 'to': 1, 'total_deposit': 1000000000000000000, 'balance': 1000000000000000000}}, {'assert': {'from': 1, 'to': 2, 'total_deposit': 1000000000000000000, 'balance': 1000000000000000000}}, {'assert': {'from': 2, 'to': 3, 'total_deposit': 1000000000000000000, 'balance': 1000000000000000000}}, {'assert_pfs_iou': {'source': 0, 'amount': 50000000000000000}}]}}, {'serial': {'name': 'Check that shortest path was used', 'tasks': [{'assert_pfs_history': {'source': 0, 'request_count': 1, 'target': 3, 'routes_count': 1, 'expected_routes': [[0, 4, 3]]}}]}}, {'serial': {'name': \"Stop node 4 to make sure that path isn't used again\", 'tasks': [{'stop_node': 4}]}}, {'serial': {'name': 'Make payment from 0 to 3 after node4 is stopped', 'tasks': [{'wait_blocks': 1}, {'transfer': {'from': 0, 'to': 3, 'amount': 1000000000000000, 'expected_http_status': 200}}, {'wait_blocks': 1}, {'assert': {'from': 0, 'to': 1, 'total_deposit': 1000000000000000000, 'balance': 999000000000000000}}, {'assert': {'from': 1, 'to': 2, 'total_deposit': 1000000000000000000, 'balance': 999000000000000000}}, {'assert': {'from': 2, 'to': 3, 'total_deposit': 1000000000000000000, 'balance': 999000000000000000}}, {'assert_pfs_iou': {'source': 0, 'amount': 100000000000000000}}]}}, {'serial': {'name': 'Check that the [0, 1, 2, 3] path was used', 'tasks': [{'assert_pfs_history': {'source': 0, 'request_count': 2, 'target': 3, 'routes_count': 1, 'expected_routes': [[0, 4, 3], [0, 1, 2, 3]]}}]}}]}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "greenlet_name": "orchestration",
  "timestamp": "2021-08-18 19:31:29.815649",
  "exception": "Traceback (most recent call last):\n  File \"/scenario-player/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/scenario-player/scenario_player/tasks/execution.py\", line 36, in _run\n    task()\n  File \"/scenario-player/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/scenario-player/scenario_player/tasks/execution.py\", line 36, in _run\n    task()\n  File \"/scenario-player/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/scenario-player/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:42039/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0xd87d36705F7278240CA2e9EA14cE6f5f4F051024. Expected 200: {\"errors\": \"Payment couldn't be completed because: PFS: Could not connect to Pathfinding Service (HTTPSConnectionPool(host='pfs.transport01.raiden.network', port=443): Read timed out. (read timeout=10.0))\"}"
}
```

`node_5045_000/run-5045.stderr`
```
--------- Starting ---------
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 500, in _wrapped_initialize_web_rtc
    self._initialize_web_rtc(address)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 521, in _initialize_web_rtc
    self._add_connection(partner_address, conn)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 537, in _add_connection
    assert partner_address not in self._address_to_connection, "must not be there already"
AssertionError: must not be there already
2021-08-18T19:22:46Z <Greenlet "Greenlet<fn:_wrapped_initialize_web_rtc>" at 0x7c88383b6830: <bound method WebRTCManager._wrapped_initialize_web_rtc of <raiden.network.transport.matrix.rtc.web_rtc.WebRTCManager object at 0x7c883975b4d0>>(b'\xb83W\xcc\xaf\xc9\xe1\xd7c\x92\xca.W%\xa4\xef\x)> failed with AssertionError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 500, in _wrapped_initialize_web_rtc
    self._initialize_web_rtc(address)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 521, in _initialize_web_rtc
    self._add_connection(partner_address, conn)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 537, in _add_connection
    assert partner_address not in self._address_to_connection, "must not be there already"
AssertionError: must not be there already
2021-08-18T19:22:46Z <Greenlet "Greenlet<fn:_wrapped_initialize_web_rtc>" at 0x7c883848b710: <bound method WebRTCManager._wrapped_initialize_web_rtc of <raiden.network.transport.matrix.rtc.web_rtc.WebRTCManager object at 0x7c883975b4d0>>(b'\xb83W\xcc\xaf\xc9\xe1\xd7c\x92\xca.W%\xa4\xef\x)> failed with AssertionError
```

`node_5045_001/run-5045.stderr`
```
--------- Starting ---------
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 500, in _wrapped_initialize_web_rtc
    self._initialize_web_rtc(address)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 521, in _initialize_web_rtc
    self._add_connection(partner_address, conn)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 537, in _add_connection
    assert partner_address not in self._address_to_connection, "must not be there already"
AssertionError: must not be there already
2021-08-18T19:21:16Z <Greenlet "Greenlet<fn:_wrapped_initialize_web_rtc>" at 0x744a87f5d830: <bound method WebRTCManager._wrapped_initialize_web_rtc of <raiden.network.transport.matrix.rtc.web_rtc.WebRTCManager object at 0x744a952b9850>>(b'\xc2\x8d\xfb\x90\xc8\xb59\xcb\xce\xdb\xfc\x92\x8)> failed with AssertionError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 500, in _wrapped_initialize_web_rtc
    self._initialize_web_rtc(address)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 521, in _initialize_web_rtc
    self._add_connection(partner_address, conn)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 537, in _add_connection
    assert partner_address not in self._address_to_connection, "must not be there already"
AssertionError: must not be there already
2021-08-18T19:21:16Z <Greenlet "Greenlet<fn:_wrapped_initialize_web_rtc>" at 0x744a87f5da70: <bound method WebRTCManager._wrapped_initialize_web_rtc of <raiden.network.transport.matrix.rtc.web_rtc.WebRTCManager object at 0x744a952b9850>>(b'\xc2\x8d\xfb\x90\xc8\xb59\xcb\xce\xdb\xfc\x92\x8)> failed with AssertionError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 500, in _wrapped_initialize_web_rtc
    self._initialize_web_rtc(address)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 521, in _initialize_web_rtc
    self._add_connection(partner_address, conn)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 537, in _add_connection
    assert partner_address not in self._address_to_connection, "must not be there already"
AssertionError: must not be there already
2021-08-18T19:21:16Z <Greenlet "Greenlet<fn:_wrapped_initialize_web_rtc>" at 0x744a87e37710: <bound method WebRTCManager._wrapped_initialize_web_rtc of <raiden.network.transport.matrix.rtc.web_rtc.WebRTCManager object at 0x744a952b9850>>(b'\x90\xf05\xe8\x1f\xd5\xaf?\xc6\x19\xcc\xed\t\x14)> failed with AssertionError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 500, in _wrapped_initialize_web_rtc
    self._initialize_web_rtc(address)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 521, in _initialize_web_rtc
    self._add_connection(partner_address, conn)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 537, in _add_connection
    assert partner_address not in self._address_to_connection, "must not be there already"
AssertionError: must not be there already
2021-08-18T19:21:16Z <Greenlet "Greenlet<fn:_wrapped_initialize_web_rtc>" at 0x744a87e37830: <bound method WebRTCManager._wrapped_initialize_web_rtc of <raiden.network.transport.matrix.rtc.web_rtc.WebRTCManager object at 0x744a952b9850>>(b'\x90\xf05\xe8\x1f\xd5\xaf?\xc6\x19\xcc\xed\t\x14)> failed with AssertionError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 500, in _wrapped_initialize_web_rtc
    self._initialize_web_rtc(address)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 521, in _initialize_web_rtc
    self._add_connection(partner_address, conn)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 537, in _add_connection
    assert partner_address not in self._address_to_connection, "must not be there already"
AssertionError: must not be there already
2021-08-18T19:21:16Z <Greenlet "Greenlet<fn:_wrapped_initialize_web_rtc>" at 0x744a87e37b90: <bound method WebRTCManager._wrapped_initialize_web_rtc of <raiden.network.transport.matrix.rtc.web_rtc.WebRTCManager object at 0x744a952b9850>>(b'\x90\xf05\xe8\x1f\xd5\xaf?\xc6\x19\xcc\xed\t\x14)> failed with AssertionError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 500, in _wrapped_initialize_web_rtc
    self._initialize_web_rtc(address)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 521, in _initialize_web_rtc
    self._add_connection(partner_address, conn)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 537, in _add_connection
    assert partner_address not in self._address_to_connection, "must not be there already"
AssertionError: must not be there already
2021-08-18T19:21:45Z <Greenlet "Greenlet<fn:_wrapped_initialize_web_rtc>" at 0x744a87f5def0: <bound method WebRTCManager._wrapped_initialize_web_rtc of <raiden.network.transport.matrix.rtc.web_rtc.WebRTCManager object at 0x744a952b9850>>(b'\x90\xf05\xe8\x1f\xd5\xaf?\xc6\x19\xcc\xed\t\x14)> failed with AssertionError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 500, in _wrapped_initialize_web_rtc
    self._initialize_web_rtc(address)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 521, in _initialize_web_rtc
    self._add_connection(partner_address, conn)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 537, in _add_connection
    assert partner_address not in self._address_to_connection, "must not be there already"
AssertionError: must not be there already
2021-08-18T19:21:45Z <Greenlet "Greenlet<fn:_wrapped_initialize_web_rtc>" at 0x744a87e374d0: <bound method WebRTCManager._wrapped_initialize_web_rtc of <raiden.network.transport.matrix.rtc.web_rtc.WebRTCManager object at 0x744a952b9850>>(b'\x90\xf05\xe8\x1f\xd5\xaf?\xc6\x19\xcc\xed\t\x14)> failed with AssertionError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 500, in _wrapped_initialize_web_rtc
    self._initialize_web_rtc(address)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 521, in _initialize_web_rtc
    self._add_connection(partner_address, conn)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 537, in _add_connection
    assert partner_address not in self._address_to_connection, "must not be there already"
AssertionError: must not be there already
2021-08-18T19:22:16Z <Greenlet "Greenlet<fn:_wrapped_initialize_web_rtc>" at 0x744a87e37950: <bound method WebRTCManager._wrapped_initialize_web_rtc of <raiden.network.transport.matrix.rtc.web_rtc.WebRTCManager object at 0x744a952b9850>>(b'\x90\xf05\xe8\x1f\xd5\xaf?\xc6\x19\xcc\xed\t\x14)> failed with AssertionError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 500, in _wrapped_initialize_web_rtc
    self._initialize_web_rtc(address)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 521, in _initialize_web_rtc
    self._add_connection(partner_address, conn)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 537, in _add_connection
    assert partner_address not in self._address_to_connection, "must not be there already"
AssertionError: must not be there already
2021-08-18T19:22:16Z <Greenlet "Greenlet<fn:_wrapped_initialize_web_rtc>" at 0x744a87e37290: <bound method WebRTCManager._wrapped_initialize_web_rtc of <raiden.network.transport.matrix.rtc.web_rtc.WebRTCManager object at 0x744a952b9850>>(b'\x90\xf05\xe8\x1f\xd5\xaf?\xc6\x19\xcc\xed\t\x14)> failed with AssertionError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 500, in _wrapped_initialize_web_rtc
    self._initialize_web_rtc(address)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 521, in _initialize_web_rtc
    self._add_connection(partner_address, conn)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 537, in _add_connection
    assert partner_address not in self._address_to_connection, "must not be there already"
AssertionError: must not be there already
2021-08-18T19:22:46Z <Greenlet "Greenlet<fn:_wrapped_initialize_web_rtc>" at 0x744a87f5d170: <bound method WebRTCManager._wrapped_initialize_web_rtc of <raiden.network.transport.matrix.rtc.web_rtc.WebRTCManager object at 0x744a952b9850>>(b'\x90\xf05\xe8\x1f\xd5\xaf?\xc6\x19\xcc\xed\t\x14)> failed with AssertionError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 500, in _wrapped_initialize_web_rtc
    self._initialize_web_rtc(address)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 521, in _initialize_web_rtc
    self._add_connection(partner_address, conn)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 537, in _add_connection
    assert partner_address not in self._address_to_connection, "must not be there already"
AssertionError: must not be there already
2021-08-18T19:22:46Z <Greenlet "Greenlet<fn:_wrapped_initialize_web_rtc>" at 0x744a9405dcb0: <bound method WebRTCManager._wrapped_initialize_web_rtc of <raiden.network.transport.matrix.rtc.web_rtc.WebRTCManager object at 0x744a952b9850>>(b'\x90\xf05\xe8\x1f\xd5\xaf?\xc6\x19\xcc\xed\t\x14)> failed with AssertionError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 500, in _wrapped_initialize_web_rtc
    self._initialize_web_rtc(address)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 521, in _initialize_web_rtc
    self._add_connection(partner_address, conn)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 537, in _add_connection
    assert partner_address not in self._address_to_connection, "must not be there already"
AssertionError: must not be there already
2021-08-18T19:23:16Z <Greenlet "Greenlet<fn:_wrapped_initialize_web_rtc>" at 0x744a87d45290: <bound method WebRTCManager._wrapped_initialize_web_rtc of <raiden.network.transport.matrix.rtc.web_rtc.WebRTCManager object at 0x744a952b9850>>(b'\x90\xf05\xe8\x1f\xd5\xaf?\xc6\x19\xcc\xed\t\x14)> failed with AssertionError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 500, in _wrapped_initialize_web_rtc
    self._initialize_web_rtc(address)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 521, in _initialize_web_rtc
    self._add_connection(partner_address, conn)
  File "/root/.cache/pypoetry/virtualenvs/scenario-player-BbLh1Wrj-py3.7/lib/python3.7/site-packages/raiden/network/transport/matrix/rtc/web_rtc.py", line 537, in _add_connection
    assert partner_address not in self._address_to_connection, "must not be there already"
AssertionError: must not be there already
2021-08-18T19:23:16Z <Greenlet "Greenlet<fn:_wrapped_initialize_web_rtc>" at 0x744a87d45950: <bound method WebRTCManager._wrapped_initialize_web_rtc of <raiden.network.transport.matrix.rtc.web_rtc.WebRTCManager object at 0x744a952b9850>>(b'\x90\xf05\xe8\x1f\xd5\xaf?\xc6\x19\xcc\xed\t\x14)> failed with AssertionError
```

**Comment by istankovic** [comment] 2021-09-10 11:32
Duplicate of #690.

**Closed by istankovic** 2021-09-10 11:32 UTC
Labels: bug
