### ISSUE TITLE
Transaction [txhash] failed

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#238] opened 2019-08-15 15:02 UTC
Description
=========
Today when trying to start a new scenario I run into the error shown in the attached logfile.
[scenario-player-run_pfs7_multiple_payments_2019-08-15T16:54:56.log](https://github.com/raiden-network/scenario-player/files/3505967/scenario-player-run_pfs7_multiple_payments_2019-08-15T16.54.56.log)

It seems that a tx fails when trying to call `deposit` in the UDC contract. The problem also happens on old scenarios that I've run earlier today.

I tried installing the SP in a fresh venv too, but the problems persists.

This is on latest dev branch of the SP and of Raiden.

Expected Behavior
===============
I expected the SP to start the scenario as usual and to fund the nodes correctly.

**Comment by czepluch** [comment] 2019-08-15 15:46
Tried to use both the bb eth node vpn and my dappcon node, but same problem occurs.

**Comment by eorituz** [comment] 2019-08-16 09:47
So I can't reproduce the error.
Your error code points to a reverted [onchain Tx](https://goerli.etherscan.io/tx/0xb508c34739260b6031e96deed105783edc0306c9b7addbe470789656c2f91ce4)
No clue what goes wrong here, but it works fine for me atm.

**Comment by Dominik1999** [comment] 2019-08-16 09:52
I reproduced the error. I first successfully ran a scenario, then, when I simply want to re-run it, I get the same error. 

```
{"result": "scenario error", "event": "Run finished", "logger": "scenario_player.main", "level": "error", "timestamp": "2019-08-16 09:46:51.021767", "exception": "Traceback (most recent call last):\n  File \"/home/pirate/PycharmProjects/ScenarioPlayer/scenario-player/scenario_player/main.py\", line 179, in run\n    runner.run_scenario()\n  File \"/home/pirate/PycharmProjects/ScenarioPlayer/scenario-player/scenario_player/runner.py\", line 224, in run_scenario\n    wait_for_txs(self.client, fund_tx | ud_token_tx | mint_tx)\n  File \"/home/pirate/PycharmProjects/ScenarioPlayer/scenario-player/scenario_player/utils/legacy.py\", line 193, in wait_for_txs\n    raise ScenarioTxError(f\"Transaction {encode_hex(txhash)} failed.\")\nscenario_player.exceptions.legacy.ScenarioTxError: Transaction 0xe8195f306388726e7810eb84d5e1e1bac96fc884eb67ad13fc3c09998bbd77e3 failed."}
```

Now it constantly fails with this error

**Comment by eorituz** [comment] 2019-08-16 10:23
@Dominik1999 That's wired since your "first" deposit Tx went through (https://goerli.etherscan.io/tx/0xb74dcdfa5820bbf9d2bf38b395c5eb83e6808f0d7ed505ca22a2b548d1d58156) but the second one failed.
Which scenario did you run?

**Comment by Dominik1999** [comment] 2019-08-16 11:15
I ran https://github.com/raiden-network/raiden/pull/4619/files

but it also happens with any other scenario now. Probably the deposit is not increasing, because the SP uses the same nodes (Eth addresses) and tries to deposit as defined in the scenario

one of these `require()` isn't fulfilled probably.
``` 
function deposit(address beneficiary, uint256 new_total_deposit)
        external
    {
        require(new_total_deposit > total_deposit[beneficiary], "deposit not increasing");

        // Calculate the actual amount of tokens that will be transferred
        uint256 added_deposit = new_total_deposit - total_deposit[beneficiary];

        balances[beneficiary] += added_deposit;
        total_deposit[beneficiary] += added_deposit;

        // Update whole_balance, but take care against overflows.
        require(whole_balance + added_deposit >= whole_balance, "overflowing deposit");
        whole_balance += added_deposit;

        // Decline deposit if the whole balance is bigger than the limit.
        require(whole_balance <= whole_balance_limit, "too much deposit");

        // Actual transfer.
        require(token.transferFrom(msg.sender, address(this), added_deposit), "tokens didn't transfer");
```

**Comment by eorituz** [comment] 2019-08-16 12:46
Mhh I still can't reproduce the error.
Not even if I reuse already used addresses on purpose...
@Dominik1999 could you provide me with the exact command you ran as well as the content of your `~./raiden/scenario-player/scenarios/pfs7_multiple_payments` folder?

**Comment by eorituz** [comment] 2019-08-16 12:49
I even ran the scenario without any trouble even though I used previously used Addresses on purpose... 
(Since we're always deploying a new token for every run there should be no conflict with already existing balances in any SC.)

**Comment by czepluch** [comment] 2019-08-16 13:13
@Dominik1999 what you explain is exactly what happened to me too.

**Comment by nlsdfnbch** [comment] 2019-08-19 08:45
Running scenarios on `0.3.1`, I cannot reproduce this locally.

**Comment by Dominik1999** [comment] 2019-08-19 09:14
here are my logs @eorituz 

I can reproduce it every time

[Test-Fails-Transaction-UDC.zip](https://github.com/raiden-network/scenario-player/files/3515027/Test-Fails-Transaction-UDC.zip)

**Comment by eorituz** [comment] 2019-08-19 09:48
Since I won't be able to fix it until Wednesday, I'll unassign me for now.

**Comment by eorituz** [comment] 2019-08-30 12:19
So apparently we still have trouble with deposit function calls.
Some of them fail with no obvious pattern.

You can check my tx history [here](https://goerli.etherscan.io/address/0xbac08a75b9fcd0f3c510a61aec2c864fb3dbbb27).
All Tx in block 1209528 & 1209530 belong to one scenario player run. (Only one deposit fails)
Another player-run are the Tx in block 1209685 and 1209686. (Three deposits fail)

@hackaugusto could you please also have a look at it?

**Comment by hackaugusto** [comment] 2019-08-30 12:54
The initial comment has the following stacktrace:

```
Traceback (most recent call last):
  File "/home/jacob/dev/venvs/sp_venv/lib/python3.7/site-packages/scenario_player/main.py", line 179, in run
    runner.ru
n_scenario()
  File "/home/jacob/dev/venvs/sp_venv/lib/python3.7/site-packages/scenario_player/runner.py", line 224, in run_scenario
    wait_for_txs(self.client, fund_tx |
ud_token_tx | mint_tx)
  File "/home/jacob/dev/venvs/sp_venv/lib/python3.7/site-packages/scenario_player/utils/legacy.py", line 193, in wait_for_txs
    raise ScenarioTxErro
r(f"Transaction {encode_hex(txhash)} failed.")
scenario_player.exceptions.legacy.ScenarioTxError: Transaction 0xb508c34739260b6031e96deed105783edc0306c9b7addbe470789656c2f91c
e4 failed.
```

The transaction [0xb508c34739260b6031e96deed105783edc0306c9b7addbe470789656c2f91c](https://goerli.etherscan.io/tx/0xb508c34739260b6031e96deed105783edc0306c9b7addbe470789656c2f91ce4) is a deposit that reverted. The transaction was mined at block 1124179.

The transaction was sent by `0x0bae0289AAA26845224F528F9B9DefE69e01606E` to the user deposit `0xdE6c9977D903Ff978E24f06DC4d78FA49486094E`, depositing for `0x263726Baa4606153cEc023fd294E55e15ec391B5` an amount of  `5000` tokens.

These are the requires for the `deposit` function:

```
        require(new_total_deposit > total_deposit[beneficiary], "deposit not increasing");
        require(whole_balance + added_deposit >= whole_balance, "overflowing deposit");
        require(whole_balance <= whole_balance_limit, "too much deposit");
        require(token.transferFrom(msg.sender, address(this), added_deposit), "tokens didn't transfer");
```

And these are the requires for the `transferFrom`:

```
        require(balances[_from] >= _value);
        require(allowed[_from][msg.sender] >= _value);
        require(_value > 0);
```

I used the following setup:

```python
from web3 import HTTPProvider, Web3
from raiden_contracts.contract_manager import ContractManager, contracts_precompiled_path
from raiden_contracts.constants import CONTRACT_CUSTOM_TOKEN, CONTRACT_USER_DEPOSIT
from eth_utils import to_checksum_address

web3 = Web3(HTTPProvider('http://localhost:port_number'))
contract_manager = ContractManager(contracts_precompiled_path())
ud = web3.eth.contract(abi=contract_manager.get_contract_abi(CONTRACT_USER_DEPOSIT), address='0xdE6c9977D903Ff978E24f06DC4d78FA49486094E')
token = web3.eth.contract(abi=contract_manager.get_contract_abi(CONTRACT_CUSTOM_TOKEN), address=ud.functions.token().call())
```
And executed the following queries:
```
>>> ud.functions.total_deposit('0x263726Baa4606153cEc023fd294E55e15ec391B5').call(block_identifier=1124179)
0
>>> ud.functions.whole_balance().call(block_identifier=1124179)
47000000000000004041000
>>> ud.functions.whole_balance_limit().call(block_identifier=1124179)
115792089237316195423570985008687907853269984665640564039457584007913129639935
>>> token.functions.balanceOf('0x0bae0289AAA26845224F528F9B9DefE69e01606E').call(block_identifier=1124179)
0
>>> token.functions.allowance('0x0bae0289AAA26845224F528F9B9DefE69e01606E', '0xdE6c9977D903Ff978E24f06DC4d78FA49486094E').call(block_identifier=1124179)
15000
```
So, the problem is that the address `0x0bae0289AAA26845224F528F9B9DefE69e01606E` doesn't have any tokens to transfer.

**Comment by eorituz** [comment] 2019-08-30 13:21
@hackaugusto I think there is a misunderstanding. In Jacobs code the `Token` is `"0xb06bA27e1cc31aa7d16f0B9303Da6Bf23885Fd7F"`. And the beneficiary does have 10.000 of those tokens. 
The Token Address thing that you pulled out of the logs is something else (pls don't ask me what it is :D )

**Comment by hackaugusto** [comment] 2019-08-30 13:26
So, I followed the logs, and the scenario player is calling the `mint` function, turns out the address had a balance of `10000` until the block `1124178`. At the block `1124179` the following happened:


```python
>>> from web3.utils.abi import filter_by_type
>>> from eth_utils import event_abi_to_log_topic
>>> from web3.utils.events import get_event_data
>>> topic_to_event_abi = {event_abi_to_log_topic(event_abi): event_abi for event_abi in filter_by_type('event', token.events.abi)}
>>> [get_event_data(topic_to_event_abi[log['topics'][0]], log) for log in web3.eth.getLogs({'address': '0x2D64D0d6C3892f58B7698C8520ba12ee02998F00', 'fromBlock': 1124178, 'toBlock': 1124190})]
[AttributeDict({'args': AttributeDict({'_from': '0x0bae0289AAA26845224F528F9B9DefE69e01606E', '_to': '0xdE6c9977D903Ff978E24f06DC4d78FA49486094E', '_value': 5000}), 'event': 'Transfer', 'logIndex': 44, 'transactionIndex': 44, 'transactionHash': HexBytes('0x926a169a3dd41b99d1db7709bda3410bd24695d19268de28de2dbdafe4dbb5c0'), 'address': '0x2D64D0d6C3892f58B7698C8520ba12ee02998F00', 'blockHash': HexBytes('0xc871d5fff14637cbbcf4a07e2ca4eb1f274f9a49de8bddd8c992cc37fc3d1e76'), 'blockNumber': 1124179}),
 AttributeDict({'args': AttributeDict({'_from': '0x0bae0289AAA26845224F528F9B9DefE69e01606E', '_to': '0xdE6c9977D903Ff978E24f06DC4d78FA49486094E', '_value': 5000}), 'event': 'Transfer', 'logIndex': 46, 'transactionIndex': 46, 'transactionHash': HexBytes('0xf6e550196aa35cab2cccb22d2346e834963082138487acef4ae87baa3a0822ac'), 'address': '0x2D64D0d6C3892f58B7698C8520ba12ee02998F00', 'blockHash': HexBytes('0xc871d5fff14637cbbcf4a07e2ca4eb1f274f9a49de8bddd8c992cc37fc3d1e76'), 'blockNumber': 1124179})]
```

These are the two transactions:

https://goerli.etherscan.io/tx/0xf6e550196aa35cab2cccb22d2346e834963082138487acef4ae87baa3a0822ac
https://goerli.etherscan.io/tx/0x926a169a3dd41b99d1db7709bda3410bd24695d19268de28de2dbdafe4dbb5c0

**Comment by hackaugusto** [comment] 2019-08-30 13:29
@eorituz I pulled the address directly from the user deposit smart contract, `ud.functions.token().call()`

**Comment by eorituz** [comment] 2019-08-30 14:21
@hackaugusto  thanks, that makes sense...
So to me, it looks like something more fundamental is broken.
The handling around when which, for whom and how much tokens should be minted.
(During the PFS7 scenario run e.g. plenty of tokens get minted but never used?)

**Comment by hackaugusto** [comment] 2019-08-30 14:48
@ulope found the problem:

The problem is that `Contract.mint` uses `self.config.token.max_funding - balance`, while `UserDepositContract.deposit` uses `self.config.settings.services.udc.token.balance_per_node`

The first defaults to `DEFAULT_TOKEN_BALANCE_FUND = 10_000`, while the second is set in the scenario to `balance_per_node: 20000`

**Comment by christianbrb** [comment] 2019-08-30 15:19
From a timing perspective this could have been introduced with https://github.com/raiden-network/scenario-player/pull/221 released with https://github.com/raiden-network/scenario-player/releases/tag/v0.3.0

**Comment by eorituz** [comment] 2019-08-30 15:22
## So Here's the deal:
I can this scenario [pfs7_multiple_payments.zip](https://github.com/raiden-network/scenario-player/files/3560524/pfs7_multiple_payments.zip) it's basically the same as jacob suggested but with `settings.services.udc.token.balance_per_node = token.balance_min = 20000`

### Scenario player command
```
--chain goerli:http://geth.goerli.ethnodes.brainbot.com:8545 run --keystore-file keystore/UTC--1  --password 123 --no-ui /home/oliver/Arbeit/github/scenario-player/test_scenarios/pfs7_multiple_payments.yaml


### Raiden version
```
(scenario_player) oliver@bbpc:~/Arbeit/github/scenario-player$ raiden version
{
  "raiden": "0.100.5.dev3+g3a6642643",
  "raiden_db_version": 23,
  "python_implementation": "CPython",
  "python_version": "3.7.1",
  "system": "Linux 64bit_ELF 4.15.0-58-generic",
  "architecture": "x86_64",
  "distribution": "source"
}
```

**Comment by ulope** [comment] 2019-09-02 17:23
Seems @hackaugusto found the issue.

`Contract.balance` (which is inherited by `Token` and `UserDepositContract`) is querying the account's eth balance not the token balance:
https://github.com/raiden-network/scenario-player/blob/3f87cc464cf8974a3ac69acc6266336d5edd70ac/scenario_player/utils/token.py#L39-L40

#275 corrects this. A brief local test seems to confirm that the txs now are preformed correctly.

**Comment by hackaugusto** [comment] 2019-09-02 17:30
The scenario player logs don't have enough information for me to pin down exactly what happened. So I'm fetched all logs from the token:

```python
from collections import defaultdict

token_address = '0x2D64D0d6C3892f58B7698C8520ba12ee02998F00'
scenario_node_address = '0x0bae0289AAA26845224F528F9B9DefE69e01606E'
sender_transaction = defaultdict(list)
hash_to_log = defaultdict(list)
all_logs = web3.eth.getLogs({'address': token_address, 'fromBlock': 1008864, 'toBlock': 1124190})
decoded_logs = [get_event_data(topic_to_event_abi[log['topics'][0]], log) for log in all_logs]
transactions = [web3.eth.getTransaction(l['transactionHash']) for l in decoded_logs]
for t in transactions:
  sender_transaction[t['from']].append(t)
for l in decoded_logs:
  hash_to_log[l['transactionHash']].append(l)
events_from_scenario = [hash_to_log[t['hash']] for t in sender_transaction[to_checksum_address('0x0bae0289aaa26845224f528f9b9defe69e01606e')]]

result = 0
for t, v in [(e['event'], e['args'].get('_value') or e['args'].get('_num')) for e in events_from_scenario]:
   if t == 'Transfer': result -= v
   if t == 'Minted': result += v
```

`result` is 0, here are [the events](https://gist.github.com/hackaugusto/8197b49a7fbfde4df6d2ca1769951cad)

**Comment by hackaugusto** [comment] 2019-09-02 18:56
Okay, I found the problem. The explanation bellow assumes the code from `v0.3.0-dev` (this is important because of the values in the `constants.py`):

- The call to [mint](https://github.com/raiden-network/scenario-player/blob/v0.3.0-dev/scenario_player/runner.py#L277-L279) per node address is useless. Because the scenario player cannot use these tokens.
- The only [call to `mint`](https://github.com/raiden-network/scenario-player/blob/v0.3.0-dev/scenario_player/runner.py#L316-L318) that is useful for the run is done during `_initialize_udc`. This will end up executing [this code](https://github.com/raiden-network/scenario-player/blob/v0.3.0-dev/scenario_player/utils/token.py#L71-L86).
- The formula to compute how many tokens should be minted is `self.config.token.max_funding - self.balance`. `self.balance` is probably mistakenly the [ether balance of **the UDC smart contract**](https://github.com/raiden-network/scenario-player/blob/v0.3.0-dev/scenario_player/utils/token.py#L38-L40), which is always zero. This means the amount of tokens is always `max_funding`.
- For the logs I was following, we [know that 10_000 tokens were minted](https://github.com/raiden-network/scenario-player/issues/238#issuecomment-527210969). [Which was the default for v0.3.0-dev](https://github.com/raiden-network/scenario-player/blob/v0.3.0-dev/scenario_player/constants.py#L9). I also assume that the scenario executed was the one linked [above](https://github.com/raiden-network/scenario-player/issues/238#issuecomment-521975114), which [does not overwrite the default](https://github.com/raiden-network/raiden/blob/6225a8e3fe34ae4a3a5e60ac69c8bc6cf2293da7/raiden/tests/scenarios/pfs7_multiple_payments.yaml#L15-L17)

The solution here should be simple, just like [update allowance](https://github.com/raiden-network/scenario-player/blob/v0.3.0-dev/scenario_player/utils/token.py#L362-L388), a update mint of sort has to be introduced, and replace the call to mint that is not enough.

**Closed** 2019-09-03 12:48 UTC
Labels: bug
